### ISSUE TITLE
Tag-Along not working

### ISSUE THREAD

**Issue by debyeleong** [MicrosoftDocs/mixed-reality#325]
The Unity build and Visual Studio deployment to my HoloLens were successful but the Tag-Along functionality was not working.  When I played the game scene in Unity, I got:

MissingComponentException: There is no 'Renderer' attached to the "AstroMan" game object, but a script is trying to access it.
You probably need to add a Renderer to the game object "AstroMan". Or your script needs to check if the component is attached before using it.
UnityEngine.Renderer.get_materials () (at C:/buildslave/unity/build/Runtime/Export/GraphicsRenderers.bindings.cs:80)
Interactible.Start () (at Assets/Scripts/Interactible.cs:17)

Any suggestion would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c49bf7f-19f2-3dae-0a5c-562ef686e4ea
* Version Independent ID: 6bf4877d-e20b-e055-1ee4-ab6d5d6c7976
* Content: [Holograms 210 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-210)
* Content Source: [mixed-reality-docs/holograms-210.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/holograms-210.md)
* Service: **unspecified**
* GitHub Login: @keveleigh
* Microsoft Alias: **kurtie**

**Comment by mattzmsft** [comment]
@keveleigh @davidkline-mis Can you guys take a look at this and see if some detail is missing from the Holograms 210 steps for implementing tag-along that might be affecting @debyeleong?

Thanks,
Matt

**Comment by keveleigh** [comment]
Thanks for catching this! Turns out it was caused by an errant step that isn't necessary to complete the course. I've addressed this in #335.

**Comment by ThreeTreeTrolls** [comment]
Still having some trouble with the Tag-Along portion of the tutorial. Not getting any errors but astronaut doesn't tag-along or billboard after chapter 6. The billboarding portion worked fine in the previous chapter and I'm following the instructions and downloaded files from #335. 

Any idea what's going on/any more details I can provide to help find a solution?

**Comment by keveleigh** [comment]
@ThreeTreeTrolls 

#335 refers to some archived pages that no longer exist. Are you following the updated tutorial here: https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-210?

I believe the steps to tagalong the astronaut have been removed, and the steps for billboarding the astronaut are undone at the end of chapter 5.

![image](https://user-images.githubusercontent.com/3580640/41313826-ce2ad08a-6e3f-11e8-9d5b-ff8d34878a4b.png)

**Comment by ThreeTreeTrolls** [comment]
@keveleigh
I had originally followed the updated tutorial and ran into issues with Billboarding (the astronaut was facing the wrong direction - the fix was in the other closed discussion.) and Tag along. Since the fix worked I tried to follow #335 but tag along didn't seem to be working from there either. 
I've given the updated tutorial from your link another try, but tag along and billboarding does not seem to be working after building Chapter 6. (I have remembered to delete the script from AstroMan before moving on to the next step). 

Any idea what might be going wrong?

**Comment by MaksAMillion** [comment]
@ThreeTreeTrolls 
On the billboard.cs script I changed the direction to the following so that the astronaut will face the user:
Vector3 directionToTarget = transform.position - TargetTransform.position;
(basically transform.position was swapped with TargetTransform.position)

&& that will cause the Tagalong to face the opposite direction.
and this causes the UI billboard tagalong to face away making it not visible. So, continue in the project window inside the holograms folder into the Tagalong prefab, clicking the little arrow will open up the children of that gameObject. Then, still in the Project window select the child of Tagalong, ui_transform and change the Y value of the rotation of the transform in the inspector to 180.


I believe the UI's and gameObject's normal direction is somehow different, so when the astronaut faces the user we cannot see the ui and when the astronaut faces away the UI is visible. (they both have a billboard component attached)
